few_shots = [
    {
        'Question': "How many tracks are there from the 'Rock' genre?",
        'SQLQuery': "SELECT COUNT(*) FROM Track JOIN Genre ON Track.GenreId = Genre.GenreId WHERE Genre.Name = 'Rock'",
        'SQLResult': "Result of the SQL query",
        'Answer': "There are 1297 tracks from the 'Rock' genre."
    },
    {
        'Question': "What is the total duration of all tracks by the artist 'AC/DC'?",
        'SQLQuery': """SELECT SUM(Milliseconds / 60000) FROM Track
                       JOIN Album ON Track.AlbumId = Album.AlbumId
                       JOIN Artist ON Album.ArtistId = Artist.ArtistId
                       WHERE Artist.Name = 'AC/DC'""",
        'SQLResult': "Result of the SQL query",
        'Answer': "The total duration of all tracks by the artist 'AC/DC' is 80 minutes."
    },
    {
        'Question': "How much revenue has been generated from all purchases of 'Classical' tracks?",
        'SQLQuery': """SELECT SUM(InvoiceLine.UnitPrice * InvoiceLine.Quantity) FROM InvoiceLine
                       JOIN Track ON InvoiceLine.TrackId = Track.TrackId
                       JOIN Genre ON Track.GenreId = Genre.GenreId
                       WHERE Genre.Name = 'Classical'""",
        'SQLResult': "Result of the SQL query",
        'Answer': "The total revenue generated from all purchases of 'Classical' tracks is approximately $40.59."
    },
    {
        'Question': "How many albums do we have from the 'Metallica' artist?",
        'SQLQuery': """SELECT COUNT(*) FROM Album
                       JOIN Artist ON Album.ArtistId = Artist.ArtistId
                       WHERE Artist.Name = 'Metallica'""",
        'SQLResult': "Result of the SQL query",
        'Answer': "We have 10 albums from the 'Metallica' artist."
    },
    {
        'Question': "What is the total revenue generated by the customer 'Frank Harris'?",
        'SQLQuery': """SELECT SUM(Invoice.Total) FROM Invoice
                       JOIN Customer ON Invoice.CustomerId = Customer.CustomerId
                       WHERE Customer.FirstName = 'Frank' AND Customer.LastName = 'Harris'""",
        'SQLResult': "Result of the SQL query",
        'Answer': "The total revenue generated by the customer 'Frank Harris' is $37.62."
    }
]